package vvgnabava.otvorenipostupak;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Description("Interna odluka o imenovanju ovlastenih predstavnika")
public class InternaOdlukaIOP implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "ID_odlukaIOP")
   private java.lang.Integer ID_odlukaIOP;
   @org.kie.api.definition.type.Label(value = "BrojOdlukeIOP")
   private java.lang.String brojOdlukeIOP;
   @org.kie.api.definition.type.Label(value = "DatumOdlukeIOP")
   private java.util.Date datumOdlukeIOP;

   public InternaOdlukaIOP()
   {
   }

   public java.lang.Integer getID_odlukaIOP()
   {
      return this.ID_odlukaIOP;
   }

   public void setID_odlukaIOP(java.lang.Integer ID_odlukaIOP)
   {
      this.ID_odlukaIOP = ID_odlukaIOP;
   }

   public java.lang.String getBrojOdlukeIOP()
   {
      return this.brojOdlukeIOP;
   }

   public void setBrojOdlukeIOP(java.lang.String brojOdlukeIOP)
   {
      this.brojOdlukeIOP = brojOdlukeIOP;
   }

   public java.util.Date getDatumOdlukeIOP()
   {
      return this.datumOdlukeIOP;
   }

   public void setDatumOdlukeIOP(java.util.Date datumOdlukeIOP)
   {
      this.datumOdlukeIOP = datumOdlukeIOP;
   }

   public InternaOdlukaIOP(java.lang.Integer ID_odlukaIOP,
         java.lang.String brojOdlukeIOP, java.util.Date datumOdlukeIOP)
   {
      this.ID_odlukaIOP = ID_odlukaIOP;
      this.brojOdlukeIOP = brojOdlukeIOP;
      this.datumOdlukeIOP = datumOdlukeIOP;
   }

}