package vvgnabava.otvorenipostupak;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InternaOdlukaIOP implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public InternaOdlukaIOP() {
    }

}