package vvgnabava.otvorenipostupak;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("ODLUKA O PO?ETKU POSTUPKA")
@org.kie.api.definition.type.Description("Sadrži opisni dio o po?etku postupka i o ovlaštenim predstavnicima naru?itelja")
public class ODLUKA_PP implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("id_odluke")
   private java.lang.Integer id_odluke;
   @org.kie.api.definition.type.Label("opis")
   private java.lang.String opis;

   @org.kie.api.definition.type.Label(value = "predstavnici")
   private java.util.List<vvgnabava.otvorenipostupak.OVLASTENI_PREDSTAVNICI> predstavnici;

   public ODLUKA_PP()
   {
   }

   public java.lang.Integer getId_odluke()
   {
      return this.id_odluke;
   }

   public void setId_odluke(java.lang.Integer id_odluke)
   {
      this.id_odluke = id_odluke;
   }

   public java.lang.String getOpis()
   {
      return this.opis;
   }

   public void setOpis(java.lang.String opis)
   {
      this.opis = opis;
   }

   public java.util.List<vvgnabava.otvorenipostupak.OVLASTENI_PREDSTAVNICI> getPredstavnici()
   {
      return this.predstavnici;
   }

   public void setPredstavnici(
         java.util.List<vvgnabava.otvorenipostupak.OVLASTENI_PREDSTAVNICI> predstavnici)
   {
      this.predstavnici = predstavnici;
   }

   public ODLUKA_PP(
         java.lang.Integer id_odluke,
         java.lang.String opis,
         java.util.List<vvgnabava.otvorenipostupak.OVLASTENI_PREDSTAVNICI> predstavnici)
   {
      this.id_odluke = id_odluke;
      this.opis = opis;
      this.predstavnici = predstavnici;
   }

}