package vvgnabava.otvorenipostupak;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ODLUKA_PP implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ODLUKA_PP() {
    }

}