package vvgnabava.otvorenipostupak;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("OVLASTENI PREDSTAVNICI")
@org.kie.api.definition.type.Description("Popis ovlaštenih predstavnika naru?itelja")
public class OVLASTENI_PREDSTAVNICI implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("id_predstavnika")
   @javax.persistence.Id
   private java.lang.Integer id_predstavnika;
   @org.kie.api.definition.type.Label("ime_prezime")
   private java.lang.String ime_prezime;

   public OVLASTENI_PREDSTAVNICI()
   {
   }

   public java.lang.Integer getId_predstavnika()
   {
      return this.id_predstavnika;
   }

   public void setId_predstavnika(java.lang.Integer id_predstavnika)
   {
      this.id_predstavnika = id_predstavnika;
   }

   public java.lang.String getIme_prezime()
   {
      return this.ime_prezime;
   }

   public void setIme_prezime(java.lang.String ime_prezime)
   {
      this.ime_prezime = ime_prezime;
   }

   public OVLASTENI_PREDSTAVNICI(java.lang.Integer id_predstavnika,
         java.lang.String ime_prezime)
   {
      this.id_predstavnika = id_predstavnika;
      this.ime_prezime = ime_prezime;
   }

}