package vvgnabava.otvorenipostupak;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class POJASNJENE_DOKUMENTACIJA implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public POJASNJENE_DOKUMENTACIJA() {
    }

}