package vvgnabava.otvorenipostupak;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("PredmetNabave")
@org.kie.api.definition.type.Description("Sadrži sve relevantne podatke o postupku nabave.")
public class PredmetNabave implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "ID_predmeta")
   private java.lang.Integer ID_predmeta;
   @org.kie.api.definition.type.Label(value = "EBN")
   private java.lang.String EBN;
   @org.kie.api.definition.type.Label(value = "OpisPredmeta")
   private java.lang.String opisPredmeta;
   @org.kie.api.definition.type.Label(value = "InternaOdlukaIOP")
   private vvgnabava.otvorenipostupak.InternaOdlukaIOP internaOdlukaIOP;
   @org.kie.api.definition.type.Label(value = "Ponuda")
   private java.util.List<vvgnabava.otvorenipostupak.PonudaZalba> ponuda;

   public PredmetNabave()
   {
   }

   public java.lang.Integer getID_predmeta()
   {
      return this.ID_predmeta;
   }

   public void setID_predmeta(java.lang.Integer ID_predmeta)
   {
      this.ID_predmeta = ID_predmeta;
   }

   public java.lang.String getEBN()
   {
      return this.EBN;
   }

   public void setEBN(java.lang.String EBN)
   {
      this.EBN = EBN;
   }

   public java.lang.String getOpisPredmeta()
   {
      return this.opisPredmeta;
   }

   public void setOpisPredmeta(java.lang.String opisPredmeta)
   {
      this.opisPredmeta = opisPredmeta;
   }

   public vvgnabava.otvorenipostupak.InternaOdlukaIOP getInternaOdlukaIOP()
   {
      return this.internaOdlukaIOP;
   }

   public void setInternaOdlukaIOP(
         vvgnabava.otvorenipostupak.InternaOdlukaIOP internaOdlukaIOP)
   {
      this.internaOdlukaIOP = internaOdlukaIOP;
   }

   public java.util.List<vvgnabava.otvorenipostupak.PonudaZalba> getPonuda()
   {
      return this.ponuda;
   }

   public void setPonuda(
         java.util.List<vvgnabava.otvorenipostupak.PonudaZalba> ponuda)
   {
      this.ponuda = ponuda;
   }

   public PredmetNabave(java.lang.Integer ID_predmeta, java.lang.String EBN,
         java.lang.String opisPredmeta,
         vvgnabava.otvorenipostupak.InternaOdlukaIOP internaOdlukaIOP,
         java.util.List<vvgnabava.otvorenipostupak.PonudaZalba> ponuda)
   {
      this.ID_predmeta = ID_predmeta;
      this.EBN = EBN;
      this.opisPredmeta = opisPredmeta;
      this.internaOdlukaIOP = internaOdlukaIOP;
      this.ponuda = ponuda;
   }

}