package vvgnabava.otvorenipostupak;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("PREDMET NABAVE")
@org.kie.api.definition.type.Description("Sadrži sve relevantne podatke o predmetu nabave")
public class PREDMET_NABAVE implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "id_predmeta")
   private java.lang.Integer id_predmeta;
   @org.kie.api.definition.type.Label(value = "ebn")
   private java.lang.String ebn;
   @org.kie.api.definition.type.Label(value = "opis_predmeta")
   private java.lang.String opis_predmeta;
   @org.kie.api.definition.type.Label(value = "datum_pokretanja")
   private java.util.Date datum_popkretanja;

   public PREDMET_NABAVE()
   {
   }

   public java.lang.Integer getId_predmeta()
   {
      return this.id_predmeta;
   }

   public void setId_predmeta(java.lang.Integer id_predmeta)
   {
      this.id_predmeta = id_predmeta;
   }

   public java.lang.String getEbn()
   {
      return this.ebn;
   }

   public void setEbn(java.lang.String ebn)
   {
      this.ebn = ebn;
   }

   public java.lang.String getOpis_predmeta()
   {
      return this.opis_predmeta;
   }

   public void setOpis_predmeta(java.lang.String opis_predmeta)
   {
      this.opis_predmeta = opis_predmeta;
   }

   public java.util.Date getDatum_popkretanja()
   {
      return this.datum_popkretanja;
   }

   public void setDatum_popkretanja(java.util.Date datum_popkretanja)
   {
      this.datum_popkretanja = datum_popkretanja;
   }

   public PREDMET_NABAVE(java.lang.Integer id_predmeta, java.lang.String ebn,
         java.lang.String opis_predmeta, java.util.Date datum_popkretanja)
   {
      this.id_predmeta = id_predmeta;
      this.ebn = ebn;
      this.opis_predmeta = opis_predmeta;
      this.datum_popkretanja = datum_popkretanja;
   }

}