package vvgnabava.otvorenipostupak;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("PREDMET NABAVE")
@org.kie.api.definition.type.Description("Sadrži sve relevantne podatke o predmetu nabave")
public class PREDMET_NABAVE implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("id_predmeta")
   private java.lang.Integer id_predmeta;
   @org.kie.api.definition.type.Label("ebn")
   private java.lang.String ebn;
   @org.kie.api.definition.type.Label("opis_predmeta")
   private java.lang.String opis_predmeta;
   @org.kie.api.definition.type.Label("datum_pokretanja")
   private java.util.Date datum_popkretanja;

   @org.kie.api.definition.type.Label("odluka_pp")
   private vvgnabava.otvorenipostupak.ODLUKA_PP odluka_pp;

   @org.kie.api.definition.type.Label(value = "ponuda")
   private java.util.List<vvgnabava.otvorenipostupak.PONUDA> ponuda;

   @org.kie.api.definition.type.Label(value = "zalba")
   private java.util.List<vvgnabava.otvorenipostupak.ZALBA> zalba;

   @org.kie.api.definition.type.Label(value = "zapisnik_uvid_ponude")
   private java.util.List<vvgnabava.otvorenipostupak.ZAPISNIK_UVID_PON> zapisnik_uvid_ponude;

   public PREDMET_NABAVE()
   {
   }

   public java.lang.Integer getId_predmeta()
   {
      return this.id_predmeta;
   }

   public void setId_predmeta(java.lang.Integer id_predmeta)
   {
      this.id_predmeta = id_predmeta;
   }

   public java.lang.String getEbn()
   {
      return this.ebn;
   }

   public void setEbn(java.lang.String ebn)
   {
      this.ebn = ebn;
   }

   public java.lang.String getOpis_predmeta()
   {
      return this.opis_predmeta;
   }

   public void setOpis_predmeta(java.lang.String opis_predmeta)
   {
      this.opis_predmeta = opis_predmeta;
   }

   public java.util.Date getDatum_popkretanja()
   {
      return this.datum_popkretanja;
   }

   public void setDatum_popkretanja(java.util.Date datum_popkretanja)
   {
      this.datum_popkretanja = datum_popkretanja;
   }

   public vvgnabava.otvorenipostupak.ODLUKA_PP getOdluka_pp()
   {
      return this.odluka_pp;
   }

   public void setOdluka_pp(vvgnabava.otvorenipostupak.ODLUKA_PP odluka_pp)
   {
      this.odluka_pp = odluka_pp;
   }

   public java.util.List<vvgnabava.otvorenipostupak.PONUDA> getPonuda()
   {
      return this.ponuda;
   }

   public void setPonuda(java.util.List<vvgnabava.otvorenipostupak.PONUDA> ponuda)
   {
      this.ponuda = ponuda;
   }

   public java.util.List<vvgnabava.otvorenipostupak.ZALBA> getZalba()
   {
      return this.zalba;
   }

   public void setZalba(java.util.List<vvgnabava.otvorenipostupak.ZALBA> zalba)
   {
      this.zalba = zalba;
   }

   public java.util.List<vvgnabava.otvorenipostupak.ZAPISNIK_UVID_PON> getZapisnik_uvid_ponude()
   {
      return this.zapisnik_uvid_ponude;
   }

   public void setZapisnik_uvid_ponude(
         java.util.List<vvgnabava.otvorenipostupak.ZAPISNIK_UVID_PON> zapisnik_uvid_ponude)
   {
      this.zapisnik_uvid_ponude = zapisnik_uvid_ponude;
   }

   public PREDMET_NABAVE(
         java.lang.Integer id_predmeta,
         java.lang.String ebn,
         java.lang.String opis_predmeta,
         java.util.Date datum_popkretanja,
         vvgnabava.otvorenipostupak.ODLUKA_PP odluka_pp,
         java.util.List<vvgnabava.otvorenipostupak.PONUDA> ponuda,
         java.util.List<vvgnabava.otvorenipostupak.ZALBA> zalba,
         java.util.List<vvgnabava.otvorenipostupak.ZAPISNIK_UVID_PON> zapisnik_uvid_ponude)
   {
      this.id_predmeta = id_predmeta;
      this.ebn = ebn;
      this.opis_predmeta = opis_predmeta;
      this.datum_popkretanja = datum_popkretanja;
      this.odluka_pp = odluka_pp;
      this.ponuda = ponuda;
      this.zalba = zalba;
      this.zapisnik_uvid_ponude = zapisnik_uvid_ponude;
   }

}