package vvgnabava.otvorenipostupak;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Description("Popis mogu?ih stanja postupka")
@org.kie.api.definition.type.Label("StatusPredmeta")
public class SatusPredmeta implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "ID_status")
   private java.util.List<java.lang.Integer> ID_status;
   @org.kie.api.definition.type.Label(value = "OpisStatusa")
   private java.util.List<java.lang.String> opisStatusa;

   public SatusPredmeta()
   {
   }

   public java.util.List<java.lang.Integer> getID_status()
   {
      return this.ID_status;
   }

   public void setID_status(java.util.List<java.lang.Integer> ID_status)
   {
      this.ID_status = ID_status;
   }

   public java.util.List<java.lang.String> getOpisStatusa()
   {
      return this.opisStatusa;
   }

   public void setOpisStatusa(java.util.List<java.lang.String> opisStatusa)
   {
      this.opisStatusa = opisStatusa;
   }

   public SatusPredmeta(java.util.List<java.lang.Integer> ID_status,
         java.util.List<java.lang.String> opisStatusa)
   {
      this.ID_status = ID_status;
      this.opisStatusa = opisStatusa;
   }

}