package vvgnabava.otvorenipostupak;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ZALBA_ODAB_PON implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ZALBA_ODAB_PON() {
    }

}