package vvgnabava.otvorenipostupak;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ZAP_PREG_OCJ_PON implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ZAP_PREG_OCJ_PON() {
    }

}