package vvgnabava.otvorenipostupak;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("ZAPISNIK O PREGLEDU I OCJENI PONUDA")
@org.kie.api.definition.type.Description("Izra?uje se nakon otvaranja ponuda.")
public class ZAP_PREG_OCJ_PON implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "id_zapisnika")
   private java.lang.Integer id_zapisnika;
   @org.kie.api.definition.type.Label(value = "ebn")
   private java.lang.String ebn;
   @org.kie.api.definition.type.Label(value = "datum")
   private java.util.Date datum;

   public ZAP_PREG_OCJ_PON()
   {
   }

   public java.lang.Integer getId_zapisnika()
   {
      return this.id_zapisnika;
   }

   public void setId_zapisnika(java.lang.Integer id_zapisnika)
   {
      this.id_zapisnika = id_zapisnika;
   }

   public java.lang.String getEbn()
   {
      return this.ebn;
   }

   public void setEbn(java.lang.String ebn)
   {
      this.ebn = ebn;
   }

   public java.util.Date getDatum()
   {
      return this.datum;
   }

   public void setDatum(java.util.Date datum)
   {
      this.datum = datum;
   }

   public ZAP_PREG_OCJ_PON(java.lang.Integer id_zapisnika,
         java.lang.String ebn, java.util.Date datum)
   {
      this.id_zapisnika = id_zapisnika;
      this.ebn = ebn;
      this.datum = datum;
   }

}