package vvgnabava.otvorenipostupak;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ZAPISNIK_OTV_PON implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.Id
   @org.kie.api.definition.type.Label(value = "id_zapisnika_OP")
   private java.lang.Integer id_zapisnikaOP;
   @org.kie.api.definition.type.Label(value = "opis")
   private java.lang.String opis;

   public ZAPISNIK_OTV_PON()
   {
   }

   public java.lang.Integer getId_zapisnikaOP()
   {
      return this.id_zapisnikaOP;
   }

   public void setId_zapisnikaOP(java.lang.Integer id_zapisnikaOP)
   {
      this.id_zapisnikaOP = id_zapisnikaOP;
   }

   public java.lang.String getOpis()
   {
      return this.opis;
   }

   public void setOpis(java.lang.String opis)
   {
      this.opis = opis;
   }

   public ZAPISNIK_OTV_PON(java.lang.Integer id_zapisnikaOP,
         java.lang.String opis)
   {
      this.id_zapisnikaOP = id_zapisnikaOP;
      this.opis = opis;
   }

}