package vvgnabava.otvorenipostupak;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ZAPISNIK_OTV_PON implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ZAPISNIK_OTV_PON() {
    }

}